#[doc = "Register `HCCONTROL` reader"]
pub struct R(crate::R<HCCONTROL_SPEC>);
impl core::ops::Deref for R {
    type Target = crate::R<HCCONTROL_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl From<crate::R<HCCONTROL_SPEC>> for R {
    #[inline(always)]
    fn from(reader: crate::R<HCCONTROL_SPEC>) -> Self {
        R(reader)
    }
}
#[doc = "Register `HCCONTROL` writer"]
pub struct W(crate::W<HCCONTROL_SPEC>);
impl core::ops::Deref for W {
    type Target = crate::W<HCCONTROL_SPEC>;
    #[inline(always)]
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl core::ops::DerefMut for W {
    #[inline(always)]
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
impl From<crate::W<HCCONTROL_SPEC>> for W {
    #[inline(always)]
    fn from(writer: crate::W<HCCONTROL_SPEC>) -> Self {
        W(writer)
    }
}
#[doc = "Field `CBSR` reader - ControlBulkServiceRatio."]
pub type CBSR_R = crate::FieldReader<u8, u8>;
#[doc = "Field `CBSR` writer - ControlBulkServiceRatio."]
pub type CBSR_W<'a> = crate::FieldWriter<'a, u32, HCCONTROL_SPEC, u8, u8, 2, 0>;
#[doc = "Field `PLE` reader - PeriodicListEnable."]
pub type PLE_R = crate::BitReader<bool>;
#[doc = "Field `PLE` writer - PeriodicListEnable."]
pub type PLE_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 2>;
#[doc = "Field `IE` reader - IsochronousEnable."]
pub type IE_R = crate::BitReader<bool>;
#[doc = "Field `IE` writer - IsochronousEnable."]
pub type IE_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 3>;
#[doc = "Field `CLE` reader - ControlListEnable."]
pub type CLE_R = crate::BitReader<bool>;
#[doc = "Field `CLE` writer - ControlListEnable."]
pub type CLE_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 4>;
#[doc = "Field `BLE` reader - BulkListEnable This bit is set to enable the processing of the Bulk list in the next Frame."]
pub type BLE_R = crate::BitReader<bool>;
#[doc = "Field `BLE` writer - BulkListEnable This bit is set to enable the processing of the Bulk list in the next Frame."]
pub type BLE_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 5>;
#[doc = "Field `HCFS` reader - HostControllerFunctionalState for USB 00b: USBRESET 01b: USBRESUME 10b: USBOPERATIONAL 11b: USBSUSPEND A transition to USBOPERATIONAL from another state causes SOFgeneration to begin 1 ms later."]
pub type HCFS_R = crate::FieldReader<u8, u8>;
#[doc = "Field `HCFS` writer - HostControllerFunctionalState for USB 00b: USBRESET 01b: USBRESUME 10b: USBOPERATIONAL 11b: USBSUSPEND A transition to USBOPERATIONAL from another state causes SOFgeneration to begin 1 ms later."]
pub type HCFS_W<'a> = crate::FieldWriter<'a, u32, HCCONTROL_SPEC, u8, u8, 2, 6>;
#[doc = "Field `IR` reader - InterruptRouting This bit determines the routing of interrupts generated by events registered in HcInterruptStatus."]
pub type IR_R = crate::BitReader<bool>;
#[doc = "Field `IR` writer - InterruptRouting This bit determines the routing of interrupts generated by events registered in HcInterruptStatus."]
pub type IR_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 8>;
#[doc = "Field `RWC` reader - RemoteWakeupConnected This bit indicates whether HC supports remote wake-up signaling."]
pub type RWC_R = crate::BitReader<bool>;
#[doc = "Field `RWC` writer - RemoteWakeupConnected This bit indicates whether HC supports remote wake-up signaling."]
pub type RWC_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 9>;
#[doc = "Field `RWE` reader - RemoteWakeupEnable This bit is used by HCD to enable or disable the remote wake-up feature upon the detection of upstream resume signaling."]
pub type RWE_R = crate::BitReader<bool>;
#[doc = "Field `RWE` writer - RemoteWakeupEnable This bit is used by HCD to enable or disable the remote wake-up feature upon the detection of upstream resume signaling."]
pub type RWE_W<'a> = crate::BitWriter<'a, u32, HCCONTROL_SPEC, bool, 10>;
impl R {
    #[doc = "Bits 0:1 - ControlBulkServiceRatio."]
    #[inline(always)]
    pub fn cbsr(&self) -> CBSR_R {
        CBSR_R::new((self.bits & 3) as u8)
    }
    #[doc = "Bit 2 - PeriodicListEnable."]
    #[inline(always)]
    pub fn ple(&self) -> PLE_R {
        PLE_R::new(((self.bits >> 2) & 1) != 0)
    }
    #[doc = "Bit 3 - IsochronousEnable."]
    #[inline(always)]
    pub fn ie(&self) -> IE_R {
        IE_R::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bit 4 - ControlListEnable."]
    #[inline(always)]
    pub fn cle(&self) -> CLE_R {
        CLE_R::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - BulkListEnable This bit is set to enable the processing of the Bulk list in the next Frame."]
    #[inline(always)]
    pub fn ble(&self) -> BLE_R {
        BLE_R::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bits 6:7 - HostControllerFunctionalState for USB 00b: USBRESET 01b: USBRESUME 10b: USBOPERATIONAL 11b: USBSUSPEND A transition to USBOPERATIONAL from another state causes SOFgeneration to begin 1 ms later."]
    #[inline(always)]
    pub fn hcfs(&self) -> HCFS_R {
        HCFS_R::new(((self.bits >> 6) & 3) as u8)
    }
    #[doc = "Bit 8 - InterruptRouting This bit determines the routing of interrupts generated by events registered in HcInterruptStatus."]
    #[inline(always)]
    pub fn ir(&self) -> IR_R {
        IR_R::new(((self.bits >> 8) & 1) != 0)
    }
    #[doc = "Bit 9 - RemoteWakeupConnected This bit indicates whether HC supports remote wake-up signaling."]
    #[inline(always)]
    pub fn rwc(&self) -> RWC_R {
        RWC_R::new(((self.bits >> 9) & 1) != 0)
    }
    #[doc = "Bit 10 - RemoteWakeupEnable This bit is used by HCD to enable or disable the remote wake-up feature upon the detection of upstream resume signaling."]
    #[inline(always)]
    pub fn rwe(&self) -> RWE_R {
        RWE_R::new(((self.bits >> 10) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:1 - ControlBulkServiceRatio."]
    #[inline(always)]
    pub fn cbsr(&mut self) -> CBSR_W {
        CBSR_W::new(self)
    }
    #[doc = "Bit 2 - PeriodicListEnable."]
    #[inline(always)]
    pub fn ple(&mut self) -> PLE_W {
        PLE_W::new(self)
    }
    #[doc = "Bit 3 - IsochronousEnable."]
    #[inline(always)]
    pub fn ie(&mut self) -> IE_W {
        IE_W::new(self)
    }
    #[doc = "Bit 4 - ControlListEnable."]
    #[inline(always)]
    pub fn cle(&mut self) -> CLE_W {
        CLE_W::new(self)
    }
    #[doc = "Bit 5 - BulkListEnable This bit is set to enable the processing of the Bulk list in the next Frame."]
    #[inline(always)]
    pub fn ble(&mut self) -> BLE_W {
        BLE_W::new(self)
    }
    #[doc = "Bits 6:7 - HostControllerFunctionalState for USB 00b: USBRESET 01b: USBRESUME 10b: USBOPERATIONAL 11b: USBSUSPEND A transition to USBOPERATIONAL from another state causes SOFgeneration to begin 1 ms later."]
    #[inline(always)]
    pub fn hcfs(&mut self) -> HCFS_W {
        HCFS_W::new(self)
    }
    #[doc = "Bit 8 - InterruptRouting This bit determines the routing of interrupts generated by events registered in HcInterruptStatus."]
    #[inline(always)]
    pub fn ir(&mut self) -> IR_W {
        IR_W::new(self)
    }
    #[doc = "Bit 9 - RemoteWakeupConnected This bit indicates whether HC supports remote wake-up signaling."]
    #[inline(always)]
    pub fn rwc(&mut self) -> RWC_W {
        RWC_W::new(self)
    }
    #[doc = "Bit 10 - RemoteWakeupEnable This bit is used by HCD to enable or disable the remote wake-up feature upon the detection of upstream resume signaling."]
    #[inline(always)]
    pub fn rwe(&mut self) -> RWE_W {
        RWE_W::new(self)
    }
    #[doc = "Writes raw bits to the register."]
    #[inline(always)]
    pub unsafe fn bits(&mut self, bits: u32) -> &mut Self {
        self.0.bits(bits);
        self
    }
}
#[doc = "Defines the operating modes of the HC\n\nThis register you can [`read`](crate::generic::Reg::read), [`write_with_zero`](crate::generic::Reg::write_with_zero), [`reset`](crate::generic::Reg::reset), [`write`](crate::generic::Reg::write), [`modify`](crate::generic::Reg::modify). See [API](https://docs.rs/svd2rust/#read--modify--write-api).\n\nFor information about available fields see [hccontrol](index.html) module"]
pub struct HCCONTROL_SPEC;
impl crate::RegisterSpec for HCCONTROL_SPEC {
    type Ux = u32;
}
#[doc = "`read()` method returns [hccontrol::R](R) reader structure"]
impl crate::Readable for HCCONTROL_SPEC {
    type Reader = R;
}
#[doc = "`write(|w| ..)` method takes [hccontrol::W](W) writer structure"]
impl crate::Writable for HCCONTROL_SPEC {
    type Writer = W;
}
#[doc = "`reset()` method sets HCCONTROL to value 0"]
impl crate::Resettable for HCCONTROL_SPEC {
    #[inline(always)]
    fn reset_value() -> Self::Ux {
        0
    }
}
